export const storeData = [
    {
        id:1,
        title:'Techno Phantom',
        img:'',
        price:20,
        company:'Techno',
        info:"loremipsum dolor amet lsd klsskkk slaoel kmnvdkvkeisk lsakdfopnlbmd jsldjkfei",
        inCart: false,
        count:0,
        total:0,
    },
    {
        id:2,
        title:'Techno PoP',
        img:'',
        price:12,
        company:'Techno',
        info:"lorexcvdlsfkoawvjvdmsdfmipsum dolor amet lsd klsskkk slaoel kmnvdkvkeisk lsakdfopnlbmd jsldjkfei",
        inCart: false,
        count:0,
        total:0,
    },    {
        id:3,
        title:'Samsung Galaxy',
        img:'',
        price:22,
        company:'Samsung',
        info:"loremipsumdli lkklll is not hte  dolor amet lsd klsskkk slaoel kmnvdkvkeisk lsakdfopnlbmd jsldjkfei",
        inCart: false,
        count:0,
        total:0,
    },    {
        id:4,
        title:'Vivo altra',
        img:'',
        price:15,
        company:'Vivo',
        info:"loremip not only the slslslsum dolor amet lsd klsskkk slaoel kmnvdkvkeisk lsakdfopnlbmd jsldjkfei",
        inCart: false,
        count:0,
        total:0,
    },    {
        id:5,
        title:'iPhone 13 Pro max',
        img:'',
        price:30,
        company:'Apple',
        info:"loremipsum dolor amet lsd klsskkk slaoel kmnvdkvkeisk lsakdfopnlbmd jsldjkfei",
        inCart: false,
        count:0,
        total:0,
    },    {
        id:6,
        title:'Huawei',
        img:'',
        price:15,
        company:'Huawei',
        info:"loremips i han lsum dolor amet lsd klsskkk slaoel kmnvdkvkeisk lsakdfopnlbmd jsldjkfei",
        inCart: false,
        count:0,
        total:0,
    },    {
        id:7,
        title:'Samsung ultra 22',
        img:'',
        price:25,
        company:'Samsung',
        info:"loremipsum dolor amet lsd klsskkk slaoel kmnvdkvkeisk lsakdfopnlbmd jsldjkfei",
        inCart: false,
        count:0,
        total:0,
    },
]

export const detailData = [
    {id:7,
        title:'Samsung ultra 22',
        img:'',
        price:25,
        company:'Samsung',
        info:"loremipsum dolor amet lsd klsskkk slaoel kmnvdkvkeisk lsakdfopnlbmd jsldjkfei",
        inCart: false,
        count:0,
        total:0,}
]